### PR TITLE
CGPoint, CGSize, CGRect Conforms Hashable

### PR DESCRIPTION
**Pull request by KYHyeon**
fix https://github.com/swiftlang/swift-corelibs-foundation/issues/3443

### CODE REVIEW

**Comment by KYHyeon** [comment]
@swift-ci test

**Comment by jmschonfeld** [comment]
@KYHyeon thanks for providing this change! Since this is a change to public API, it should go through the Foundation evolution process described at https://github.com/swiftlang/swift-foundation/blob/main/Evolution.md before we land it. A pitch for this change would be great to update the non-Darwin APIs to be the same as the new Darwin APIs!

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by KYHyeon** [comment]
@jmschonfeld 
It might be something I didn't understand
Core Graphics already supports Hashable on iOS 18+.
Do I still have to go through the foundation evolution?

https://developer.apple.com/documentation/corefoundation/cgrect

**Comment by jmschonfeld** [comment]
@swift-ci please test Linux platform

**Review by jmschonfeld — APPROVED** [review]

**Pull request merged**
