### PR TITLE
[FreeBSD] Fix FreeBSD build

### PR DESCRIPTION
**Pull request by michael-yuji**
Various fixes to enable building on FreeBSD.

Fixed an issue that warning messages from libthr can be emitted to stderr when thread specific data is used. This is due to CoreFoundation setting the TSD to `CF_TSD_BAD_PTR` even after `PTHERAD_DESTRUCTOR_ITERATIONS` iterators of dtor calls. This causes libthr to emit a warning to stderr about left-over non-null TSD after max destructor iterations.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by michael-yuji** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by michael-yuji** [comment]
@swift-ci please test

**Review by parkera — APPROVED** [review]

**Comment by michael-yuji** [comment]
> Are you ready to merge this?

Yes, this pull request is ready to be merged. However, I lack write access to the repository.

**Pull request merged**
